Repository miketheman/pytest-socket, pull requests merged in 2021-12, with the labels that each got.

#85 Fix pytest-socket raises IndexError with httpx
  pyproject.toml
  pytest_socket.py
  tests/test_async.py
Labels: enhancement

#86 test: move the reenable fixture to conftest
  tests/conftest.py
  tests/test_socket.py
Labels: chore

#74 Switch to poetry-core
  pyproject.toml
Labels: enhancement, more-info-needed

#75 Handle `family` passed as keyword argument
  pytest_socket.py
  tests/test_socket.py
Labels: enhancement

#87 refactor: consolidate global options to config
  pytest_socket.py
Labels: chore

#89 chore: allow for a little complexity
  .codeclimate.yml
Labels: chore

#90 chore: remove post-yield behaviors
  pytest_socket.py
Labels: chore

#88 refactor/fix: move logic into setup phase and correct order
  pytest_socket.py
  tests/test_precedence.py
Labels: chore

#93 fix: test allow_hosts for unix sockets
  pytest_socket.py
  tests/test_combinations.py
Labels: bug

#94 chore: disable the renovate dashboard
  renovate.json
Labels: chore

#95 chore: remove verbose flag from tests
  tests/test_async.py
  tests/test_restrict_hosts.py
  tests/test_socket.py
Labels: chore

#96 test: move unix decorator to conftest
  tests/conftest.py
  tests/test_async.py
  tests/test_combinations.py
  tests/test_socket.py
Labels: chore

#97 test: randomize test order
  pyproject.toml
Labels: chore

#98 chore: update python versions
  .github/workflows/python.yml
  pyproject.toml
Labels: chore

#99 test: replace coverage command
  .github/workflows/python.yml
  Makefile
  pyproject.toml
  pytest.ini
Labels: chore

#100 chore: add isort to pre-commit
  .pre-commit-config.yaml
  pyproject.toml
  pytest_socket.py
  tests/conftest.py
  tests/test_socket.py
Labels: chore

#102 refactor: replace .format with f-strings
  pytest_socket.py
  tests/test_restrict_hosts.py
Labels: chore

#103 lint: apply black
  .flake8
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  pytest_socket.py
  tests/conftest.py
  tests/test_async.py
  tests/test_combinations.py
  tests/test_restrict_hosts.py
  tests/test_socket.py
Labels: chore
