Repository miketheman/pytest-socket, pull requests merged in 2022-01, with the labels that each got.

#109 fix: don't break on doctests
  pytest_socket.py
  tests/test_doctest.py
Labels: bug

#111 chore: update make target to handle installation
  Makefile
Labels: chore

#112 chore: add stale workflow
  .github/workflows/stale-issues.yml
Labels: chore

#115 Add Change Log project URL
  pyproject.toml
Labels: enhancement
